services:
  hpa-service:
    image: registry.digitalocean.com/stagingenv/hpa-service@sha256:05c7bdfc0c03232236919045e5ed9c0497a6ce626b12c582fe38ce85998fa6ee
    platform: linux/amd64
    networks:
      - staging_net

  gdl-website:
    image: registry.digitalocean.com/stagingenv/gdl-website@sha256:3d6e430f053b5649ee654c7f60159949d6aa655b2366ca47ec6367433d5b2b43
    platform: linux/amd64
    networks:
      - staging_net

  saveinvest-service:
    image: registry.digitalocean.com/stagingenv/saveinvest-service@sha256:60a6af5b83de064dbc4699ae848ebc02076d6b5550835246bdad9378ba37fe43
    platform: linux/amd64
    networks:
      - staging_net

  bankone-service:
    image: registry.digitalocean.com/stagingenv/bankone-service@sha256:1ef0a04bc27890e45a4d5e4eae4e578fe5a6e3af6c6e35a710651715d1a8ddb6
    platform: linux/amd64
    networks:
      - staging_net

  notification-service:
    image: registry.digitalocean.com/stagingenv/notification-service@sha256:f801cedc0349999ac001d387e79a204d24c60872dc61a131a51806fe404c2b69
    platform: linux/amd64
    networks:
      - staging_net

  loan-service:
    image: registry.digitalocean.com/stagingenv/loan-service@sha256:b1939c134856bef087ed6d0f46822a027a128ce540ffe58c3e28ab3f19b0e3d5
    platform: linux/amd64
    networks:
      - staging_net

  symplus-service:
    image: registry.digitalocean.com/stagingenv/symplus-service@sha256:7c0e2567991948a5a6cf767e37766c9e940ed6cd0ee9c9b3944c0671ef12e59f
    platform: linux/amd64
    networks:
      - staging_net

  transaction-service:
    image: registry.digitalocean.com/stagingenv/transaction-service@sha256:a61a33c3806d56c527e21e52b39fb26c45d969b88e23813cffdfcd788d7a8138
    platform: linux/amd64
    networks:
      - staging_net

  user-service:
    image: registry.digitalocean.com/stagingenv/user-service@sha256:ee1188c8414fc6ee21fda55f77930579b58ba009312d4fb96ad3a72091d7be47
    platform: linux/amd64
    networks:
      - staging_net

  dms-service:
    image: registry.digitalocean.com/stagingenv/dms-service@sha256:b2892d23f4d684c27c821ef8ffb34a19bcd616b9e066eaa33e0318d3b7097a96
    platform: linux/amd64
    networks:
      - staging_net

  account-service:
    image: registry.digitalocean.com/stagingenv/account-service@sha256:f090cc845ba6b5b78384478c386a37ed613d08a0f293ec3ce480364c25ffe4c0
    platform: linux/amd64
    networks:
      - staging_net

  nginx-proxy:
    image: nginx:stable
    platform: linux/amd64
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - user-service
      - account-service
      - transaction-service
      - dms-service
      - hpa-service
      - gdl-website
      - saveinvest-service
      - bankone-service
      - notification-service
      - loan-service
      - symplus-service
    networks:
      - staging_net

networks:
  staging_net:
    driver: bridge