version: "3.9"

networks:
  staging_net:
    driver: bridge

services:
  # --------------------------
  # Application Services
  # --------------------------
  hpa-service:
    image: registry.digitalocean.com/stagingenv/hpa-service@sha256:d03724d8f98090752c0a0a1f46bc220c184ad7c74bafff481e4a1866dd954cb2
    platform: linux/amd64
    networks:
      - staging_net

  gdl-website:
    image: registry.digitalocean.com/stagingenv/gdl-website@sha256:9366899785621f314fe349fd67100aef6733f63c0723c10bc30420020f7f935c
    platform: linux/amd64
    networks:
      - staging_net

  saveinvest-service:
    image: registry.digitalocean.com/stagingenv/saveinvest-service@sha256:e26a667f98eed019f54f44a3bfa8aa418a3b0d794b933fdd58e3bd7e73a904bc
    platform: linux/amd64
    networks:
      - staging_net

  bankone-service:
    image: registry.digitalocean.com/stagingenv/bankone-service@sha256:46373855a724ab1ca0407607a44dc76d2eb03e0624715b1f5834114190b32101
    platform: linux/amd64
    networks:
      - staging_net

  notification-service:
    image: registry.digitalocean.com/stagingenv/notification-service@sha256:776562f8f5f96382f5afe7e41492cd879a66452b96d450efbc7e75a956c22bd2
    platform: linux/amd64
    networks:
      - staging_net

  loan-service:
    image: registry.digitalocean.com/stagingenv/loans-service@sha256:fa4f4ebb735fa4e63b7f0b94d0b8ddb52644fba4bb3970fce1b396a391d1660b
    platform: linux/amd64
    networks:
      - staging_net

  symplus-service:
    image: registry.digitalocean.com/stagingenv/symplus-service@sha256:d38fda687968ec7dc569780d6fcead5b8a9c50e0007e541014d9c1643a0e2ec5
    platform: linux/amd64
    networks:
      - staging_net

  transaction-service:
    image: registry.digitalocean.com/stagingenv/transactions-service@sha256:a945aad3562918e2bf08d3e11b47d368f27fc0baad65b46473813fcacc29f977
    platform: linux/amd64
    networks:
      - staging_net

  user-service:
    image: registry.digitalocean.com/stagingenv/user-service@sha256:abe4889fff8eefe8cddc3f648aea22d203838b2918c1c746d7241e7bd1c20692
    platform: linux/amd64
    networks:
      - staging_net

  dms-service:
    image: registry.digitalocean.com/stagingenv/dms-service@sha256:a0619362988a84eff81b9b464981d506601eb4a016d87fb56f32d9ff24b8d2ca
    platform: linux/amd64
    networks:
      - staging_net

  account-service:
    image: registry.digitalocean.com/stagingenv/account-service@sha256:156dc41a2bf629cf3203f1cc25ca9e984f797c9d8bd7e15f70e80752ecb3d56a
    platform: linux/amd64
    networks:
      - staging_net

  # --------------------------
  # Nginx Reverse Proxy
  # --------------------------
  nginx-proxy:
    image: nginx:stable
    platform: linux/amd64
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro      # <-- mount full cert folder
      - /etc/nginx/proxy_params:/etc/nginx/proxy_params:ro
    depends_on:
      - user-service
      - account-service
      - transaction-service
      - dms-service
      - hpa-service
      - gdl-website
      - saveinvest-service
      - bankone-service
      - notification-service
      - loan-service
      - symplus-service
    networks:
      - staging_net