version: "2"

services:

    user-service:
      image: registry.digitalocean.com/user-service/docker.io/test/user-service@sha256:2568179285f605124aa29d2e4fca04e468b2a33c317930f2f6ad1fbc4aac02ec
      ports:
          - '3080:3080'
      environment:
          - DB_HOST=gdl-db-mysql-nyc3-49829-do-user-9991253-0.b.db.ondigitalocean.com
          - DB_PORT=25060
          - DB_USERNAME=gdldev100
          - DB_PASSWORD=yS6JVh3i3FtplyqU
          - DB_NAME=gdl

    notification-service:
        image: registry.digitalocean.com/user-service/docker.io/test/notification-service@sha256:bd52b84f1d0ee9011b851fafa4ec833c0fdd4967726326a2cd68106cf8071b19
        ports:
            - '3079:3079'
        environment:
            - DB_HOST=gdl-db-mysql-nyc3-49829-do-user-9991253-0.b.db.ondigitalocean.com
            - DB_PORT=25060
            - DB_USERNAME=gdldev100
            - DB_PASSWORD=yS6JVh3i3FtplyqU
            - DB_ROOT_PASSWORD=
            - DB_NAME=gdl
            - smtpHost=smtp.mailtrap.io
            - smtpPort=2525
            - smtpUser=2b54126b040a36
            - smtpPass=851c783623e2c7
            - secure=true

    account-service:
        image: registry.digitalocean.com/user-service/docker.io/test/account-service@sha256:583e12c39de8bfa8990d809edb3bb13d7db6237a0aa0a6ab3c41fdebfd7ef2f7
        ports:
            - '3077:3077'
        environment:
            - DB_HOST=gdl-db-mysql-nyc3-49829-do-user-9991253-0.b.db.ondigitalocean.com
            - DB_PORT=25060
            - DB_USERNAME=gdldev100
            - DB_PASSWORD=yS6JVh3i3FtplyqU
            - DB_ROOT_PASSWORD=
            - DB_NAME=gdl

    transaction-service:
        image: registry.digitalocean.com/user-service/docker.io/test/transactions-service@sha256:3f48ee73ccef61801cb21ca9f4581dec131fe8970810f29c733ccc25498ffc8a
        ports:
            - '3075:3075'
        environment:
            - DB_HOST=gdl-db-mysql-nyc3-49829-do-user-9991253-0.b.db.ondigitalocean.com
            - DB_PORT=25060
            - DB_USERNAME=gdldev100
            - DB_PASSWORD=yS6JVh3i3FtplyqU
            - DB_ROOT_PASSWORD=
            - DB_NAME=gdl

    saveinvest-service:
        image: registry.digitalocean.com/user-service/docker.io/library/saveinvest-service@sha256:f6ba52c5243f11a62d08554f3382089bf3d372daa1715f73d50b321f6f4bb445
        ports:
            - '3078:3078'
        environment:
            - DB_HOST=gdl-db-mysql-nyc3-49829-do-user-9991253-0.b.db.ondigitalocean.com
            - DB_PORT=25060
            - DB_USERNAME=gdldev100
            - DB_PASSWORD=yS6JVh3i3FtplyqU
            - DB_ROOT_PASSWORD=
            - DB_NAME=gdl

    loan-service:
        image: registry.digitalocean.com/user-service/docker.io/test/loan-service@sha256:03cf760c7ee56a9f6a837eaa7050f6853749575cbf76f1d340c3bb45e7cb2bbe
        ports:
            - '3081:3081'
        environment:
            - DB_HOST=gdl-db-mysql-nyc3-49829-do-user-9991253-0.b.db.ondigitalocean.com
            - DB_PORT=25060
            - DB_USERNAME=gdldev100
            - DB_PASSWORD=yS6JVh3i3FtplyqU
            - DB_ROOT_PASSWORD=
            - DB_NAME=gdl

    hpa-service:
        image: registry.digitalocean.com/user-service/docker.io/test/hpa-service@sha256:4d23b84634599d3daa2d70be6eeae12662b4488a18cb13f64a6283fd3fb15acb
        ports:
            - '3090:3090'
        environment:
            - DB_HOST=gdl-db-mysql-nyc3-49829-do-user-9991253-0.b.db.ondigitalocean.com
            - DB_PORT=25060
            - DB_USERNAME=gdldev100
            - DB_PASSWORD=yS6JVh3i3FtplyqU
            - DB_ROOT_PASSWORD=
            - DB_NAME=gdl