version: "3.9"

services:
  hpa-service:
    image: registry.digitalocean.com/stagingenv/hpa-service@sha256:928d25116e1310f8b2163db4aa5c3710869a3a5ce129b97026e98c4f82019fff
    networks:
      - staging_net

  gdl-website:
    image: registry.digitalocean.com/stagingenv/gdl-website@sha256:1433edf39ea85374efbb8065dc2382e27dc602e13e76d67e75760cfe28557c01
    networks:
      - staging_net

  saveinvest-service:
    image: registry.digitalocean.com/stagingenv/saveinvest-service@sha256:7aa3a89cec0ea87dc7e8b08d37954a9d5c80d4a8bccec1bc8de03286f3c7bed9
    networks:
      - staging_net

  bankone-service:
    image: registry.digitalocean.com/stagingenv/bankone-service@sha256:7d935d3b4da8b91cc4b4eb94dd3793a95ffaf3936d19b230ef6cbd9a747c969c
    networks:
      - staging_net

  notification-service:
    image: registry.digitalocean.com/stagingenv/notification-service@sha256:707e6d4dfe32b6b99437cd0abe8cb0d6472242fca9b211b2ee4e0f9af2313bba
    networks:
      - staging_net

  loan-service:
    image: registry.digitalocean.com/stagingenv/loan-service@sha256:cd9addbdc5e987d7ea80e6f3e66bde471952926b4218437a4f3a668a2232d27a
    networks:
      - staging_net

  symplus-service:
    image: registry.digitalocean.com/stagingenv/symplus-service@sha256:dba3d3c006519b142ceee6e512c0f5bf1c8477fb362d18492f48203c86605ec8
    networks:
      - staging_net

  transaction-service:
    image: registry.digitalocean.com/stagingenv/transaction-service@sha256:4b0fe7bed885d6dfda5ca2c6f82f2ef6acec0e2bb5f0992e97a2ab701c235a8d
    networks:
      - staging_net

  user-service:
    image: registry.digitalocean.com/stagingenv/user-service@sha256:30a3833a52aa20ec002c009cf2bd799762a9c125a025b95af1c4215c1e276b93
    networks:
      - staging_net

  dms-service:
    image: registry.digitalocean.com/stagingenv/dms-service@sha256:e446244f672550bbee10d4c23a1b0e4bdeae7f7d3590f91b530a07f5a13572b0
    networks:
      - staging_net

  account-service:
    image: registry.digitalocean.com/stagingenv/account-service@sha256:cb45619d669360e68739c8a338147a041b506523f4391f98f13db28105dc098b
    networks:
      - staging_net

  nginx-proxy:
    image: nginx:stable
    container_name: nginx-proxy
    ports:
      - "80:80"   # Cloudflare terminates HTTPS; Nginx only needs HTTP here
      # If you later want Nginx to handle HTTPS directly, add:
      # - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      # Optional: mount certs if you plan to enable SSL
      # - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - user-service
      - account-service
      - dms-service
      - hpa-service
      - gdl-website
      - saveinvest-service
      - bankone-service
      - notification-service
      - loan-service
      - symplus-service
      - transaction-service
    networks:
      - staging_net

networks:
  staging_net:
    driver: bridge
