version: "3.9"

networks:
  staging_net:
    driver: bridge

services:
  # --------------------------
  # Application Services
  # --------------------------
  hpa-service:
    image: registry.digitalocean.com/stagingenv/hpa-service@sha256:c75d2dd1a1f4f168364fd36968c1477a09ad2a0aa7570b40af0c5034e2bd2fb4
    platform: linux/amd64
    networks:
      - staging_net

  gdl-website:
    image: registry.digitalocean.com/stagingenv/gdl-website@sha256:9366899785621f314fe349fd67100aef6733f63c0723c10bc30420020f7f935c
    platform: linux/amd64
    networks:
      - staging_net

  saveinvest-service:
    image: registry.digitalocean.com/stagingenv/saveinvest-service@sha256:cf6cfa79bd0efe8fb3b382858e6e07f62d1dde43cbbc6c41b4f108f70e80d14f
    platform: linux/amd64
    networks:
      - staging_net

  bankone-service:
    image: registry.digitalocean.com/stagingenv/bankone-service@sha256:91b507bac8cc412c3eca85da1a049faea96095b1e7c008de3c0790b0cf12754a
    platform: linux/amd64
    networks:
      - staging_net

  notification-service:
    image: registry.digitalocean.com/stagingenv/notification-service@sha256:59ad86115e2f18709122c0cbdb37b3fd1d30ad04c1268bc8ef9cd51b8c62fe8a
    platform: linux/amd64
    networks:
      - staging_net

  loan-service:
    image: registry.digitalocean.com/stagingenv/loan-service@sha256:800c0dbcc9fb6ad1732253a5fec16b48a173c876939e9773e0f025efe3eae0c2
    platform: linux/amd64
    networks:
      - staging_net

  symplus-service:
    image: registry.digitalocean.com/stagingenv/symplus-service@sha256:f5d64fc89e9449f46abb579b208dcb7499b6f6b78815c7eca7fb1c60f276657f
    platform: linux/amd64
    networks:
      - staging_net

  transaction-service:
    image: registry.digitalocean.com/stagingenv/transactions-service@sha256:9602de25485abc8772ca637797095383b59f85a9e8f46bd2b669782ca05a6fa8
    platform: linux/amd64
    networks:
      - staging_net

  user-service:
    image: registry.digitalocean.com/stagingenv/user-service@sha256:70ba2f4ea7b106c20d50ce7071eb500fd8e3554d715cfd413a4483a208a704d4
    platform: linux/amd64
    networks:
      - staging_net

  dms-service:
    image: registry.digitalocean.com/stagingenv/dms-service@sha256:2dcbbe0b8aa82db1a5f7396ca92bf8126fb682a23d1c8549afd82291fbfe9b70
    platform: linux/amd64
    networks:
      - staging_net

  account-service:
    image: registry.digitalocean.com/stagingenv/account-service@sha256:b08f5f2789a72b1e3a5cab7712d0eaf04de234b55daba72298f141b1f1110759
    platform: linux/amd64
    networks:
      - staging_net

  # --------------------------
  # Nginx Reverse Proxy
  # --------------------------
  nginx-proxy:
    image: nginx:stable
    platform: linux/amd64
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro      # <-- mount full cert folder
      - /etc/nginx/proxy_params:/etc/nginx/proxy_params:ro
    depends_on:
      - user-service
      - account-service
      - transaction-service
      - dms-service
      - hpa-service
      - gdl-website
      - saveinvest-service
      - bankone-service
      - notification-service
      - loan-service
      - symplus-service
    networks:
      - staging_net