version: "3.9"

networks:
  staging_net:
    driver: bridge

services:
  # --------------------------
  # Application Services
  # --------------------------
  hpa-service:
    image: registry.digitalocean.com/stagingenv/hpa-service@sha256:05c7bdfc0c03232236919045e5ed9c0497a6ce626b12c582fe38ce85998fa6ee
    platform: linux/amd64
    networks:
      - staging_net

  gdl-website:
    image: registry.digitalocean.com/stagingenv/gdl-website@sha256:3d6e430f053b5649ee654c7f60159949d6aa655b2366ca47ec6367433d5b2b43
    platform: linux/amd64
    networks:
      - staging_net

  saveinvest-service:
    image: registry.digitalocean.com/stagingenv/saveinvest-service@sha256:6582976f65420d84a32a269f533e08969164e931ae8562797d23119a8f4637ba
    platform: linux/amd64
    networks:
      - staging_net

  bankone-service:
    image: registry.digitalocean.com/stagingenv/bankone-service@sha256:5dad4b7a06a2da6da374a440642e3a1ee5d29655ed2713e48308a1db860b07a2
    platform: linux/amd64
    networks:
      - staging_net

  notification-service:
    image: registry.digitalocean.com/stagingenv/notification-service@sha256:32a443ef6fe2091fa02852b297d7930b3c686964619d465bf4c02efac6b05a08
    platform: linux/amd64
    networks:
      - staging_net

  loan-service:
    image: registry.digitalocean.com/stagingenv/loan-service@sha256:b1939c134856bef087ed6d0f46822a027a128ce540ffe58c3e28ab3f19b0e3d5
    platform: linux/amd64
    networks:
      - staging_net

  symplus-service:
    image: registry.digitalocean.com/stagingenv/symplus-service@sha256:5ac91234bffce893e83e3f31b437b85f06ed73bc948ffa85b72281016e6d7ebb
    platform: linux/amd64
    networks:
      - staging_net

  transaction-service:
    image: registry.digitalocean.com/stagingenv/transactions-service@sha256:b91e1747f3a0bdf83ac136f43e0e0dcb4a7eb53974e6ce8cf1c16edbfbbfec0f
    platform: linux/amd64
    networks:
      - staging_net

  user-service:
    image: registry.digitalocean.com/stagingenv/user-service@sha256:f36336d36ad4a0ac42e54440ca87a722aeedcc282f7969c31150b0eb6ce4bdfd
    platform: linux/amd64
    networks:
      - staging_net

  dms-service:
    image: registry.digitalocean.com/stagingenv/dms-service@sha256:b2892d23f4d684c27c821ef8ffb34a19bcd616b9e066eaa33e0318d3b7097a96
    platform: linux/amd64
    networks:
      - staging_net

  account-service:
    image: registry.digitalocean.com/stagingenv/account-service@sha256:593296283d7273fad4695267ee554be2ee252abab0a0c44611ee1504b3668c9a
    platform: linux/amd64
    networks:
      - staging_net

  # --------------------------
  # Nginx Reverse Proxy
  # --------------------------
  nginx-proxy:
    image: nginx:stable
    platform: linux/amd64
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro      # <-- mount full cert folder
      - /etc/nginx/proxy_params:/etc/nginx/proxy_params:ro
    depends_on:
      - user-service
      - account-service
      - transaction-service
      - dms-service
      - hpa-service
      - gdl-website
      - saveinvest-service
      - bankone-service
      - notification-service
      - loan-service
      - symplus-service
    networks:
      - staging_net