apiVersion: v1
kind: Service
metadata:
  name: account-service
spec:
  type: NodePort
  ports:
    - port: 80  # Port on the service
      targetPort: 3077  # Port on the pods
      nodePort: 30077  # Optional: If not specified, Kubernetes will allocate a random port from the NodePort range
  selector:
    app: account-service  # Label selector to match the pods you want to expose