name: Deploy to GKE (using DOCR images)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Step 1: Install gcloud SDK (without service_account_key here)
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}

      # Step 2: Explicitly authenticate with service account key
      - name: Authenticate to Google Cloud
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' > $HOME/gcp-key.json
          gcloud auth activate-service-account --key-file=$HOME/gcp-key.json
          gcloud config set project ${{ secrets.GCP_PROJECT }}

      # Step 3: Fetch cluster credentials
      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER }}
          location: ${{ secrets.GKE_ZONE }}   # e.g. us-central1
          project_id: ${{ secrets.GCP_PROJECT }}

      # Step 4: Deploy to GKE
      - name: Deploy all manifests to GKE
        run: |
          # Apply every manifest in the repo
          kubectl apply -f .

          # Wait for all deployments in the cluster to finish rolling out
          kubectl rollout status deployment --all --timeout=5m