name: Deploy to GKE (using DOCR images)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Authenticate using the SA key
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Install gcloud CLI
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}

      # Debug step (optional, but helps confirm auth)
      - name: Verify authentication
        run: |
          gcloud auth list
          gcloud config list
          gcloud projects describe ${{ secrets.GCP_PROJECT }}

      # Get GKE credentials
      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER }}
          location: ${{ secrets.GKE_ZONE }}
          project_id: ${{ secrets.GCP_PROJECT }}

      # Deploy manifests
      - name: Deploy all manifests to GKE
        run: |
          kubectl apply -f .
          kubectl rollout status deployment --all --timeout=5m