name: Deploy to DigitalOcean Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Configure kubectl with DigitalOcean kubeconfig
      - name: Set up kubectl
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      # Deploy to Kubernetes (ignore docker-compose.yml)
      - name: Deploy to DigitalOcean Kubernetes
        run: |
          echo "Applying Kubernetes manifests..."
          # Apply only K8s manifests (skip docker-compose.yml and others)
          kubectl apply -f . --recursive --selector app!=docker-compose || true

          echo "Waiting for all deployments to roll out..."
          kubectl get deploy -o name | xargs -n1 kubectl rollout status --timeout=5m
