name: Deploy to DigitalOcean Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Configure kubectl with DigitalOcean kubeconfig
      - name: Set up kubectl
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      # Deploy to Kubernetes
      - name: Deploy to DigitalOcean Kubernetes
        run: |
          echo "Applying Kubernetes manifests..."
          kubectl apply -f ./*.yml

          echo "Waiting for all deployments to roll out..."
          kubectl rollout status deployment --all --timeout=5m
