name: Deploy to DigitalOcean Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Configure kubectl with DigitalOcean kubeconfig
      - name: Set up kubectl
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      # Deploy to Kubernetes
      - name: Deploy to DigitalOcean Kubernetes
        run: |
          echo "Applying Kubernetes manifests..."

          # Apply only manifests inside k8s/ folder (ignores docker-compose.yml, workflows, etc.)
          kubectl apply -f ./k8s --recursive

          echo "Waiting for all deployments to roll out..."
          for deploy in $(kubectl get deploy -o name); do
            kubectl rollout status "$deploy" --timeout=5m || exit 1
          done
