name: Deploy to GKE (using DOCR images)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      # 🔍 Debug step to check secret format
      - name: Debug GCP_SA_KEY format
        run: |
          echo "Secret length: ${#GCP_SA_KEY}"
          echo "First 200 chars:"
          echo "${GCP_SA_KEY}" | head -c 200
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER }}
          location: ${{ secrets.GKE_ZONE }}
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: Deploy all manifests to GKE
        run: |
          # Apply every manifest in the repo
          kubectl apply -f .

          # Wait for all deployments in the cluster to finish rolling out
          kubectl rollout status deployment --all --timeout=5m